/**
 * Delete the test users the ITC regression suite left behind.
 *
 * Every case in tests/form-first/regression.test.ts seeds a
 * participant with a formfirst-<uuid>@test.local address. Paths under
 * test (saveGoal -> syncItcGoalToTracker, runTest ->
 * createMissionForItcTest) call the participant-to-user bridge, which
 * creates a Supabase Auth user; a trigger inserts the public.users
 * row and the bridge patches it to comped. cleanup() deleted only the
 * itc_participants row, and nothing reaches the auth user once that
 * is gone, so each run left orphans: 778 of them by 2026-09-03,
 * against 25 real users, filling the admin members list.
 *
 * cleanup() now deletes the auth user too, so this is a one-off for
 * the backlog. Kept because the suite has leaked before and a clear
 * script beats an ad-hoc query written under pressure.
 *
 * SAFETY. Only addresses matching formfirst-<uuid>@test.local are
 * touched, and the pattern is machine-generated by the suite, so it
 * cannot collide with a real address. Every candidate is printed
 * before anything is deleted, and the run refuses outright if a
 * candidate does not match the pattern.
 *
 *   npx tsx scripts/purge-test-users.ts          # report only
 *   npx tsx scripts/purge-test-users.ts --apply  # delete
 */
import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });
import { createSupabaseServiceClient } from "@/lib/supabase/service";

/** The suite's own shape: formfirst-<uuid>@test.local, nothing else. */
const TEST_EMAIL =
  /^formfirst-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}@test\.local$/i;

async function main() {
  const apply = process.argv.includes("--apply");
  const supabase = createSupabaseServiceClient();

  const { data: users, error } = await supabase
    .from("users")
    .select("id, email")
    .ilike("email", "formfirst-%@test.local");
  if (error) throw new Error(error.message);

  const candidates = users ?? [];
  const bad = candidates.filter((u) => !TEST_EMAIL.test(String(u.email)));
  if (bad.length > 0) {
    console.error(
      `REFUSING: ${bad.length} row(s) matched the LIKE but not the exact pattern:`,
    );
    for (const b of bad) console.error(`  ${b.email}`);
    process.exit(1);
  }

  const { count: total } = await supabase
    .from("users")
    .select("id", { count: "exact", head: true });
  console.log(
    `${candidates.length} test users to remove, of ${total ?? "?"} total. ${
      (total ?? 0) - candidates.length
    } real users stay.`,
  );
  if (candidates.length === 0) return;

  if (!apply) {
    for (const u of candidates.slice(0, 5)) console.log(`  ${u.email}`);
    if (candidates.length > 5) console.log(`  … and ${candidates.length - 5} more`);
    console.log("\nre-run with --apply to delete");
    return;
  }

  // Delete the auth user; public.users cascades from it.
  let done = 0;
  let failed = 0;
  for (const u of candidates) {
    const { error: dErr } = await supabase.auth.admin.deleteUser(u.id as string);
    if (dErr) {
      failed += 1;
      if (failed <= 5) console.warn(`  failed ${u.email}: ${dErr.message}`);
    } else {
      done += 1;
    }
    if (done % 100 === 0 && done > 0) console.log(`  … ${done}`);
  }
  console.log(`\ndeleted ${done}${failed ? `, ${failed} failed` : ""}`);

  // Participants are separate rows and are not cascaded by the auth
  // delete; sweep any the suite left behind too.
  const { data: parts } = await supabase
    .from("itc_participants")
    .select("id, email")
    .ilike("email", "formfirst-%@test.local");
  const partIds = (parts ?? [])
    .filter((p) => TEST_EMAIL.test(String(p.email)))
    .map((p) => p.id as string);
  if (partIds.length > 0) {
    const { error: pErr } = await supabase
      .from("itc_participants")
      .delete()
      .in("id", partIds);
    console.log(
      pErr
        ? `participants: ERROR ${pErr.message}`
        : `participants: removed ${partIds.length}`,
    );
  }
}

main();
